version: '3'

services:
  elasticsearch:
    image: "elasticsearch:7.6.0"
    networks:
      - backend
    restart: always
    volumes:
      - ./elastic/ES_DATA:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
      retries: 6

  app:
    build: app/
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - ./app:/usr/share/app
    networks:
      - backend
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch

  web:
    build: web/
    restart: always
    volumes:
      - ./web:/usr/share/web
    networks:
      - backend
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
      - app

networks:
  backend: