version: '3'

services:
  elasticsearch:
    image: "elasticsearch:7.6.0"
    networks:
      - backend
    restart: always
    volumes:
      - ./elastic/ES_DATA:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
      retries: 6

  app:
    build: app/
    restart: always
    volumes:
      - ./app:/usr/share/app
    networks:
      - backend
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch

networks:
  backend: